# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZenThea' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # dépendances a installer pour notre projet :
  pod 'MessageKit'

  target 'ZenTheaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZenTheaUITests' do
    # Pods for testing
  end

end
